name: netflix
description: A new Flutter project.



publish_to: 'none' 











version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"







dependencies:
  flutter:
    sdk: flutter


  
  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^1.0.0





flutter:

  
  
  
  uses-material-design: true

  
  assets:
    - assets/images/film_1.png
    - assets/images/logo.png
    - assets/images/1.jpg
    - assets/images/2.jpg
    - assets/images/3.jpg
    - assets/images/4.jpg
    - assets/images/5.jpg
    - assets/images/6.jpg
  

  
  

  
  

  
  
  
  
  
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat.ttf
  
  
  
  
  
  
  
  
  
  
  
